apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${ORG}:${TEAM}-${ROLE}
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${ROLE}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: team:${ORG}:${TEAM}
